### ISSUE TITLE
question: output location of L refs

### ISSUE THREAD

**Issue by mpl** [fhs/acme-lsp#13]
At the moment the output of "L refs" appears in the terminal where I've started acme-lsp. I would expect it to be somewhere in acme, so I can interact with it directly (maybe in /LSP/Diagnostics ?), or maybe even directly sent to the plumber.
Am I missing something, or did I misconfigure something? or is it behaving as expected?

**Comment by fhs** [comment]
This is the expected behavior. The communication between `L` and `acme-lsp` is uni-directional: `L` asks `acme-lsp` (using plumber) to show the references to an identifier at a position in a window but `acme-lsp` can't send the answer back to `L`. So, `acme-lsp` just prints the answer to stdout.

I usually run `acme-lsp` from within `acme`, so all its output ends up in the `+Errors` window. You can also run it outside acme but with the same effect like this:
```
acme-lsp [args] 2>&1 | 9p write acme/cons
```

I know this is not ideal (and confusing), but it's the result of doing RPC using plumber. I'm still thinking if we should implement a 9P file server (or some other RPC mechanism) for a bi-direction communication between `L` and `acme-lsp`. We may need it to support more advanced LSP features.

**Comment by mpl** [comment]
yeah I was wondering if I was supposed to simply run acme-lsp from acme directly.
Makes sense, thanks.
