### ISSUE TITLE
question: disable diagnostics window?

### ISSUE THREAD

**Issue by mpl** [fhs/acme-lsp#27]
Hello,

At the moment, the diagnostics window generates so many "false positives" that it has become completely useless to me. It's usually a wall of text where actually relevant errors are near-impossible to find. I don't know if it is a misconfiguration on my part, or incompatibilities with the project(s) I am working on, or a shortcoming of acme-lsp, but that's how it is for me.

Not only is it sad that it does not do anything useful for me anymore, but the actual problem is it has also become a nuisance because whenever I do Put on a window, the diagnostics window refreshes, and sometimes the mouse pointer even jumps to it.

I would like to keep on using acme-lsp, for "L def", and automatic formatting + imports, but I would like to get rid of the diagnostics window for now. Is it possible?

thanks.

**Comment by fhs** [comment]
Diagnostics will always be sent by the LSP server but acme-lsp can hide it. I've also noticed bad diagnostics from `gopls` (e.g. when editing files for other `runtime.GOOS`). Things should improve as `gopls` becomes more stable.

I'm not sure we want to get rid of the diagnostics window entirely because we need to have at least one window open to support dump file (#15), but I can definitely add a flag to hide diagnostics. Sometimes it's useful to run tests with [`Watch go test`](https://github.com/eaburns/Watch), in which case you see diagnostics on two different windows.

**Comment by mpl** [comment]
> Diagnostics will always be sent by the LSP server but acme-lsp can hide it. I've also noticed bad diagnostics from `gopls` (e.g. when editing files for other `runtime.GOOS`). Things should improve as `gopls` becomes more stable.
> 
> I'm not sure we want to get rid of the diagnostics window entirely because we need to have at least one window open to support dump file (#15), but I can definitely add a flag to hide diagnostics. Sometimes it's useful to run tests with [`Watch go test`](https://github.com/eaburns/Watch), in which case you see diagnostics on two different windows.

Just to be clear, you're saying that when you use 'Watch go test', it would be convenient to be able to hide diagnostics, because it is redundant with the output that is in the "watch window", right?

**Comment by fhs** [comment]
> Just to be clear, you're saying that when you use 'Watch go test', it would be convenient to be able to hide diagnostics, because it is redundant with the output that is in the "watch window", right?

Right. It might be worth adding support for dynamically enabling/disabling display of diagnostics, but for now I've added a `-hidediag` flag and a corresponding `HideDiagnostics` config value.
